# Generated by Django 5.1.4 on 2025-01-03 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(choices=[('pop', 'Pop'), ('rock', 'Rock'), ('hip_hop', 'Hip-Hop'), ('jazz', 'Jazz'), ('classical', 'Classical'), ('reggae', 'Reggae'), ('electronic', 'Electronic'), ('country', 'Country'), ('blues', 'Blues'), ('metal', 'Metal')], max_length=50)),
                ('release_date', models.DateField()),
                ('bio', models.TextField()),
                ('audio_file', models.FileField(upload_to='songs/%Y/%m/%d/')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='artist.artist')),
            ],
        ),
    ]
