# Generated by Django 5.1.5 on 2025-02-01 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_remove_artist_artist_type_artist_created_at_and_more'),
        ('songs', '0002_song_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_songs', to='artist.artist'),
        ),
    ]
