# Generated by Django 5.1.4 on 2025-01-12 15:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOTMusiccrudApp', '0004_popularradio'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodayInMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='today_music/')),
                ('event_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='album_covers/'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='artist_Pic/'),
        ),
        migrations.AlterField(
            model_name='popularradio',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='radio_covers/'),
        ),
    ]
