# Generated by Django 5.1.4 on 2025-01-23 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOTMusiccrudApp', '0005_todayinmusic_alter_album_cover_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('duration', models.DurationField()),
                ('release_date', models.DateField()),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='songs/')),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='DOTMusiccrudApp.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='DOTMusiccrudApp.artist')),
            ],
        ),
    ]
