# Generated by Django 5.1.5 on 2025-02-01 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOTMusiccrudApp', '0007_songs_cover_image'),
        ('artist', '0002_remove_artist_artist_type_artist_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='artist.artist'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='artist.artist'),
        ),
        migrations.AlterModelOptions(
            name='songs',
            options={'ordering': ['-release_date'], 'verbose_name': 'Song', 'verbose_name_plural': 'Songs'},
        ),
        migrations.AlterField(
            model_name='songs',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
